
package Poglavlje16.Zadaci;

public class TextSource {
    public static final String tekst = " Googleov Android trese trÅ¾iÅ¡te ruÄnih "
            + "raÄunala i smartphoneova na veliko. Sa Androidom moÅ¾ete pisati "
            + "programe koji rade na bilo kojem kompatibilnom mobilnom ureÄ‘aju "
            + "na svijetu. Android je mobilna platforma za koju si ne moÅ¾ete "
            + "dopustiti da ne nauÄite razvijati aplikacije. Pogotovo jer je "
            + "tako lako. Pogotovo jer moÅ¾ete iskoristiti resurse koji Ä‡e vam "
            + "pomoÄ‡i da vam se to i isplati. No dobro, tako lako je malo "
            + "precijenjena izjava, treba instalirati SDK, IDE, Javu. Ups, "
            + "Javu. Tako je, razvijati za Android znaÄi razvijati aplikacije "
            + "u Javi. MoÅ¾da ne za Java virtualnu maÅ¡inu ili sa Java SDKom "
            + "ili OpenJDKom ali nauÄiti Java tehnologiju se mora. I nema "
            + "iznimke. Da bi dobro znali iskoristiti moguÄ‡nosti Androida "
            + "morate znati programirati u Javi. Ukoliko ne znate Javu nauÄite "
            + "ju, trebati Ä‡e vam. Lijepo upiÅ¡ete teÄaj za SCJD Java "
            + "programera. NauÄit Ä‡e vas svim zaÄkoljicama Java programskog "
            + "jezika. NauÄit Ä‡ete sve tehnologije koje Java koristi prilikom "
            + "razvoja programa, vjerujte, bit Ä‡e vam od neizmjerne koristi. "
            + "Od tolike koristi da Ä‡ete Android aplikacije pisati kao od "
            + "Å¡ale. MoÅ¾ete vi i knjiÅ¾ice Äitati, u knjiÅ¾icama je, a to je "
            + "poznato, saÅ¾eto svo znanje svijeta. Male slatke fine knjiÅ¾ice "
            + "napravljene od mrtvog drveÄ‡a samo za vas. Kupite si koju "
            + "knjiÅ¾icu, stavite je na stoliÄ‡ pred televiziju i nadajte se "
            + "griÅ¾nji savjesti prilikom gledanja nogometa, ili omiljenog vam "
            + "filma. Nadajte se da Ä‡e vam pogled Äesto skretati na taj mali "
            + "komadiÄ‡ umrloga drveta koje je palo samo za vas, da bi vaÅ¡e "
            + "znanje evoluiralo. Pa kad je stablo veÄ‡ podnijelo Å¾rtvu moÅ¾ete "
            + "i vi. Uzmite, otvorite i proÄitajte knjigu. Prva knjiga je "
            + "Hello, Android, Ed Burnette, The Pragmatic Bookshelfâ„¢ i "
            + "napisana je u pravom pragmatiÄnom stilu. Autor je poduzeo sve "
            + "da Äitatelja superbrzo dovede u stanje produktivnosti. Naime, "
            + "The Pragmatic Bookshelfâ„¢ je izmislio koncept Beta knjige pa do "
            + "svojih omiljenih naslova moÅ¾ete brzo i dosta aÅ¾urirano. Ja "
            + "osobno oboÅ¾avam The Pragmatic Bookshelfâ„¢ knjige i o svakoj "
            + "relevantnijoj temi imam barem jednu (Java, Groovy, Ruby, itd). "
            + "Druga knjiga je viÅ¡e set knjiga o Androidu: The Busy Coders "
            + "Guide to Android Development, The Busy Coders Guide to "
            + "Advanced Android Development i Android Programming Tutorials "
            + "autor Mark Murphy, izdavaÄ CommonsWare. Sjajne su vam to "
            + "knjiÅ¾ice, baÅ¡ nekako sjajne, a nisu ni tako skupe. TreÄ‡a knjiga "
            + "je Pro Android 2, Sayed Hashimi, Satya Komatineni, "
            + "Dave MacLean, izdavaÄ Apress, i sva je nekako profesionalna, "
            + "pa ukoliko Å¾elite biti profesionalni kupite profesionalnu "
            + "knjigu. No Å¡alu na stranu, ovo je jedna jako dobra knjiga. "
            + "Poanta, izgovor da nemate dobre literature ili da imate previÅ¡e "
            + "literature viÅ¡e ne vrijedi. Dakle moje dame i gospodo, kako "
            + "zaraditi neke Å¡uÅ¡kave novÄiÄ‡e na svemu ovome. SvaÅ¡ta su vam "
            + "priÄali: uuuu, kako ja zaradim novaca na iStoreu prodavajuÄ‡i "
            + "iPhone aplikacije. Ma da. Stvarno. Vagon dolara kaÅ¾ete. E pa i "
            + "nije to baÅ¡ tako. Da bi iPhone aplikacije bile odobrene i "
            + "puÅ¡tene u iStore, kako bih drugi korisnici mogli kupovati i vi "
            + "zaraditi za dva broda i tri vikendice na naÅ¡em toplom moru, "
            + "moraju najprije proÄ‡i provjere koda. Na iPhoneu (ili na iPadu) "
            + "se ne vrti niti jedan kod koji nije digitalno potpisan i "
            + "odobren od Applea. E toga kod Googla nema. Android platforma je "
            + "otvorena svima, svi bez iznimke mogu potpuno besplatno skinuti "
            + "alate za razvoj aplikacija i krenuti u avanturu istraÅ¾ivanja "
            + "Androida. Dovoljno je da se na mobilnom ureÄ‘aju vrti Android i "
            + "vaÅ¡a aplikacija je spremna za rad. Svoje aplikacije moÅ¾ete "
            + "distribuirati preko Android marketa. Prijava na Android market "
            + "Ä‡e vas prilikom registracije koÅ¡tati 25 USD, no alati za razvoj "
            + "su besplatni. Ukoliko Å¾elite svoje aplikacije moÅ¾ete "
            + "distribuirati korisnicima bilo kako i to potpuno besplatno, "
            + "npr otvorite svoju web stranicu. Za razliku od Applea gdje "
            + "alate za razvoj aplikacija plaÄ‡ate 99 USD, dakle platite i "
            + "prije nego ste poÄeli, a distribuirati aplikacije moÅ¾ete samo "
            + "preko iStorea. No, reÄ‡i Ä‡ete, nije ta fora sa provjerom koda "
            + "tako ni loÅ¡a, provjerava se svaki program, a izbacivanjem Flash "
            + "tehnologije zaÅ¡titili su svoje korisnike od veÄ‡ine neÅ¾eljenih "
            + "programa: virusa, malwarea, wormova, itd. Znamo za problem, "
            + "ali naÅ¡ je odabir ostaviti Android platformu toliko otvorenom "
            + "reÄ‡e jednom Androidov Å¡ef za sigurnost. Vjerojatno su to "
            + "napravili radi gadnog kaÅ¡njenja za Appleom pa se sada trude "
            + "pridobiti Å¡to veÄ‡i postotak trÅ¾iÅ¡ta ali i to je neki pokazatelj "
            + "da Google sa Androidom misli jako ozbiljno. Android je danas "
            + "najsigurnija mobilna platforma iskljuÄujuÄ‡i Appleovu paranoju "
            + "sa provjerom koda. Svega na Androidu ima, od sand box okruÅ¾enja "
            + "za aplikacije do moguÄ‡nosti paralelnog rada viÅ¡e virtualnih "
            + "maÅ¡ina (nasuprot appleovoj vrhunskoj zaÅ¡titi memorije). No ne "
            + "zavaravajmo se, malware autori joÅ¡ uvijek izbjegavaju pisanje "
            + "koda za mobilne ureÄ‘aje, no trÅ¾iÅ¡te raste i raste i raste. NeÄ‡e "
            + "tako dugo i trebati Ä‡e nam znaÄajnije bolja zaÅ¡tita ureÄ‘aja od "
            + "svih vrsta neÅ¾eljenih aplikacija. Oh, odoh ja naÅ¡iroko. Vratimo "
            + "se mi na te novÄiÄ‡e. Nisu novÄiÄ‡i baÅ¡ daleko, oni su tu, svuda "
            + "oko nas, novÄiÄ‡i nas Äekaju. Evo, ima tu taj VIPnet i njegov "
            + "Vip Android izazov, pa TCom i njegov Budi kreativan "
            + "natjeÄaj. I svi dijele neke novÄiÄ‡e, neki viÅ¡e, neki manje, "
            + "neki su puni raznih kategorija, ali su tu, u naÅ¡oj blizini. Ima "
            + "i Google Android Developers Challenge. E ima tu stvarno sjajnih "
            + "stvarÄica, prekrasnih i svjetlucavih. A jeste vidjeli prvu "
            + "nagradu. Prva nagrada je 250 tisuÄ‡ica amerikanskijeh dolariÄ‡a, "
            + "je je, 250000,00 USD, da da, neÄ‡e vas niti jedna mjenjaÄnica "
            + "primiti u Hrvatskoj, a na vratima Ä‡e vas odmah Äekati agent "
            + "porezne uprave, ako i nema poreza na znanje i kreativnost za "
            + "vas Ä‡e ga i izmisliti ako ovo osvojite. Vjerojatno se sad i "
            + "pitate: pa kad je ovaj tu autor ovog tu nepovezanoga i "
            + "nesuvislog teksta tako pametan koji vrag on ne osvoji koju "
            + "nagradu pa neka njemu kucaju na vrata. E nije vaÅ¡ autor tako "
            + "pametan i ne voli agente mister Å ukera pa neÄ‡e da mu kucaju na "
            + "vrata. Ja osobno ovo ne bi znao osvojiti, ali ako netko od vas "
            + "ovo osvoji neka odmah zove da mi plati cugu. Bit Ä‡e moj idol "
            + "for sure. Dakle, niti motivacije vam nebi trebalo prifaliti."
            + "Android pogoni Linux koji se brine za "
            + "srediÅ¡nje sustave kao Å¡to su sigurnost, upravljanje memorijom, "
            + "mreÅ¾ni stogovi i upravljanje perifernim ureÄ‘ajima. Google je "
            + "Linux namijenio kao okolinu unutar koje Ä‡e se izvrÅ¡avati sav "
            + "teÅ¾ak rad i kao platformu na kojoj Ä‡e postaviti svoju Darvik "
            + "virtualnu maÅ¡inu za procesiranje Java aplikacija. Dakle, "
            + "Android ne koristi Java virtualnu maÅ¡inu (JVM ili Sun HotSpot) "
            + "veÄ‡ Dalvik virtualnu maÅ¡inu (Dalvik VM) optimiziranu za mobilne "
            + "ureÄ‘aje baziranu na registrima. Dalvik VM ima na umu da se vaÅ¡i "
            + "programi vrte na ureÄ‘ajima ograniÄene memorije i brzine "
            + "procesora. Dalvik zna, znajte i vi. Å to znaÄi da Ä‡e se za "
            + "efektno koriÅ¡tenje Java programskog jezika na Androidu morati "
            + "malo optimizirati naÄini na koje ste do sada pisali Java "
            + "izvorni kod. Ali pazite, Dalvik koristi svoj byte code, ne Java "
            + "bytecode. Dakle zaboravite ono Å¡to ste znali i voljeli o Java "
            + "bytecodeu, nauÄite i zavolite Dalvik. Dalvik se ne naslanja na "
            + "JavaSE ili na JavaME biblioteke klasa (niti JavaME, niti AWT, "
            + "niti Swing nisu podrÅ¾ani, ode naÅ¡e znanje, ali vas sreÄ‡om tome "
            + "na Java teÄaju NetAkademije niti ne uÄe. Oni vas uÄe raznim "
            + "klasama, unutarnjim i vanjskim, suÄeljima i naprednim petljama, "
            + "kolekcijama i pobrojenjima, e toga u Dalviku ima, kako lijepo "
            + "od njih). Umjesto svega toga Dalvik koristi svoju biblioteku "
            + "napravljenu na Apache Harmony Java implementaciji. No ne "
            + "brinite, Google ima svoju povijest u tome. Npr, Googlov projekt "
            + "GWT (Google Web Toolkit) koristi Javu kao razvojni jezik ali ne "
            + "podrÅ¾ava cijeli JDK (Java development kit). Eh, Dalvik Dalvik. "
            + "Sad viÅ¡e nije dosta znati jedan preopÅ¡iran JDK, sad bi joÅ¡ "
            + "trebali znati i drugi kako bi se razvijale te krasne male "
            + "aplikacije. Ali motivacija je velika, opisana u prethodim "
            + "paragrafima pod naslovom novÄiÄ‡i. Kao dio Androida, Google je "
            + "potroÅ¡io dosta vremena razmiÅ¡ljajuÄ‡i o optimiziranju dizajna za "
            + "ureÄ‘aje s limitiranom memorijom, procesorom, a pogotovo "
            + "limitiranim izvorom napajanja koji svako malo veÄ‡e optereÄ‡enje "
            + "na procesor nagradi znaÄajnim dijelom svojeg limitiranog "
            + "energetskog izvora Å¡to se u oÄima korisnika manifestira kao "
            + "izbezumljenje i polupaniÄna potraga za malo jaÄim izvorom "
            + "energije, Äitaj zidnom utiÄnicom. Nadalje ruÄna raÄunala imaju "
            + "limitiran RAM pa se zna dogoditi da se od vrlih 64MB memorije "
            + "velikih 20MB izdvaja za rad aplikacija. Velik je taj prostor za "
            + "napredak. Taj neizmjer resursa natjerao je dizajnere da "
            + "optimiziraju sve Äega se dotaknu pa tako imamo opÅ¡irne upute o "
            + "tome kao optimizirati izvorni kod koji piÅ¡emo kako bi se "
            + "aplikacije brÅ¾e, bolje, viÅ¡e, jaÄe izvodile. Optimizacija je "
            + "to na nivou na kojem o njoj na desktop aplikacaijama nismo niti "
            + "razmiÅ¡ljali, a svodi se na: ne radi niÅ¡ta Å¡to ne moraÅ¡ i ne "
            + "diraj memoriju ukoliko ti nije izriÄito potrebna. Ukoliko "
            + "pogledamo listu paketa u Androidu vidimo da su podosta opÅ¡irne, "
            + "ima tu svega i svaÄega, lijepog i joÅ¡ ljepÅ¡eg. Prema Googlu, "
            + "sistemske biblioteke mogu iskoristiti od 10MB do 20MB, Äak i sa "
            + "optimiziranim JVMom. I zato se Google dao na posao "
            + "optimizirajuÄ‡i JVM implementaciju na svakoj moguÄ‡oj razini. "
            + "Prvo, Dalvik VM uzme generirani Java bytecode (class datoteke) "
            + "i kombinira ih u Dalvik izvrÅ¡ne datoteke (dex). Ono iskoristi "
            + "duplicirane informacije iz viÅ¡e class datoteka efektivno "
            + "reducirajuÄ‡i zahtjeve za memorijskim prostorom (nekomprimiranim "
            + "memorijskim prostorom toÄnije) za pola od tradicionalne jar "
            + "datoteke. Drugo, Google je fino ugodio garbage collector u "
            + "Dalvik VMu ali je u ranijim verzijama odluÄio izostaviti JIT "
            + "(Just In Time kompajler). Kod Dalvik MV u verziji 2 imao je "
            + "sav potreban kod za izdavanje JIT kompajlera ali on ipak nije "
            + "ukljuÄen u konaÄnom izdanju Dalvika VMa. Pretpostavlja se da "
            + "Ä‡e biti ukljuÄen u buduÄ‡nosti, ali znate kako je to s "
            + "buduÄ‡nosti. Od one da je buduÄ‡nost svijetla, preko one da nitko "
            + "ne zna Å¡to nam buduÄ‡nost donosi, do one da buduÄ‡nosti neÄ‡e niti "
            + "biti veÄ‡ Ä‡e nas neka umjetna inteligencija pojesti za svemirki "
            + "doruÄak. No sve ovisi o odnosu optimizam/pesimizam za koji ste "
            + "se odluÄili prilikom Äitanja ovog teksta. Google opravdava ovaj "
            + "potez Androidovim core bibliotekama ukljuÄujuÄ‡i i grafiÄku "
            + "bibilioteku koje su implementirane u jezicima C i C++. Npr, "
            + "Java grafiÄki API je zapravo tanka wrapper klasa oko izvornog "
            + "C++ koda koristeÄ‡i Java Native Interface (JNI). SliÄno, Android "
            + "ima i optimiziranu bibiloteku napisanu u C-u za pristup SQLite "
            + "bazi podataka, ali je ova biblioteka enkapsulirana u Java API "
            + "na viÅ¡em nivou. BuduÄ‡i da je veÄ‡ina koda napisana u jezicima C "
            + "i C++ Google je smatrao da utjecaj JITa nebi bio tako znaÄajan "
            + "na brzinu rada Dalvik VM. I konaÄno, Dalvik VM koristi drugi "
            + "tip generiranja assemblerskog koda, ne stogove veÄ‡ registre. "
            + "Google se nada da Ä‡e se ovim korakom generirati 30 posto manje "
            + "instrukcija. No napomenimo da se finalni izvrÅ¡ni kod u "
            + "Androidu, kao rezultat Dalvik VMa nije baziran na Java "
            + "bytecodu veÄ‡ na dex datotekama. To znaÄi da ne moÅ¾ete direktno "
            + "izvrÅ¡avati Java bytecode; morate poÄeti sa Java klasama i "
            + "pretvoriti ih u povezive (linkable) dex datoteke. Naravno, na "
            + "ovakvoj arhitekturi Google ja namijenio Javu kao razvojnu "
            + "platformu za aplikacije drugih proizvoÄ‘aÄa. No odluÄite li se "
            + "dublje pozabaviti Androidom naiÄ‡i Ä‡e te na Android NDK podrÅ¡ku "
            + "za native aplikacije koje se izvrÅ¡avaju direktno na Linuxu. "
            + "Pisanjem native C aplikacija moÅ¾ete dobiti 30 posto veÄ‡u brzinu "
            + "izvrÅ¡avanja alogoritama nego u Dalvik VM. Java aplikacije mogu "
            + "se ubrzati do 10 puta koristeÄ‡i JNI.";
}